#%RAML 0.8
title: HATEOAS Inc. Example API
version: v1
baseUri: http://hateoas-example.skqr.net/app_dev.php/api/{version}
mediaType: application/vnd.api+json
schemas:
  - articles: !include articles.schema.json
resourceTypes: !include resource_types.raml
traits: !include traits.raml
/articles:
  displayName: Articles
  get:
    description: Retrieves one or more articles.
    is: [paginated]
    responses:
      200:
  post:
    description: Creates one or more articles.
    responses:
      201:
  /{article-ids}:
    get:
      description: Retrieves one or more articles.
      responses:
        200:
    put:
      description: Updates one or more articles.
      responses:
        204:
    delete:
      description: Deletes one or more articles.
